@@ sequence.sql
@@ restrict_references_pragma.sql
@@ inline_pragma.sql
@@ exception_init_pragma.sql
@@ pragma
@@ expression_list.sql
@@ object_access_expression.sql
@@ model_expression.sql
@@ interval_expression.sql
@@ parameter_list.sql
@@ expression.sql
@@ plsql_identifier.sql
@@ complex_plsql_ident.sql
@@ complex_plsql_ident_elem.sql
@@ function_expression.sql
@@ datetime_expression.sql
@@ cursor_expression.sql
@@ compound_expression.sql
@@ simple_expression;
@@ boolean_expression.sql
@@ logical_term_list.sql
@@ condition.sql
@@ plsql_identifier_list.sql
@@ plsql_identifier_elem.sql
@@ expression_list_elem.sql
@@ else_clause.sql
@@ simple_case_expression.sql
@@ simple_case_elem.sql
@@ searched_case_expression.sql
@@ searched_case_statement.sql
@@ searched_case_elem.sql
@@ case_expression.sql
@@ relation.sql
@@ term.sql
@@ parameter_elem.sql
@@ flashback_query_clause.sql
@@ pivot_clause.sql
@@ unpivot_clause.sql
@@ subquery_factoring_clause.sql
@@ model_clause.sql
@@ logical_factor_list.sql
@@ boolean_term.sql
@@ boolean_factor.sql
@@ group_by_clause.sql
@@ grouping_sets_clause.sql
@@ rollup_cube_clause.sql
@@ group_by_elem.sql
@@ hierarchical_query_clause.sql
@@ where_clause.sql
@@ from_list.sql
@@ select_list.sql
@@ select_elem.sql
@@ order_by_clause.sql
@@ query_partition_clause.sql
@@ windowing_clause.sql
@@ analytic_clause.sql
@@ aggregate_function.sql
@@ order_by_elem.sql
@@ into_clause.sql
@@ query_block.sql
@@ for_update_clause.sql
@@ subquery.sql
@@ subquery_factoring_elem.sql
@@ subquery_elem.sql
@@ scalar_subquery_expression.sql
@@ scalar_datatype.sql
@@ datatype.sql
@@ cast.sql
@@ factor.sql
@@ exists_condition.sql
@@ between_condition.sql
@@ in_condition.sql
@@ null_condition.sql
@@ like_condition.sql
@@ logical_factor.sql
@@ logical_term.sql
@@ select_statement.sql
@@ variable_declaration.sql
@@ subquery_restriction_clause.sql
@@ table_collection_expression.sql
@@ query_table_expression.sql
@@ table_reference.sql
@@ join_clause.sql
@@ join_on_using.sql
@@ inner_join_clause.sql
@@ outer_join_clause.sql
@@ join_clause_elem.sql
@@ from_elem.sql
@@ constant_declaration.sql
@@ item_list_1.sql
@@ item_list_2.sql
@@ exception_declaration.sql
@@ cursor_declaration.sql
@@ item_declaration.sql
@@ parameter_declaration_list.sql
@@ parameter_declaration.sql
@@ cursor_definition.sql
@@ function_heading.sql
@@ relies_on_clause.sql
@@ function_declaration.sql
@@ nested_table_type_def.sql
@@ assoc_array_type_def.sql
@@ field_definition_list.sql
@@ subtype_definition.sql
@@ ref_cursor_type_definition.sql
@@ record_type_definition.sql
@@ field_definition.sql
@@ collection_type_definition.sql
@@ type_definition.sql
@@ procedure_heading.sql
@@ procedure_declaration.sql
@@ item_elem_1.sql
@@ declare_section.sql
@@ statement_list.sql
@@ exception_handler_list.sql
@@ body.sql
@@ plsql_block.sql
@@ procedure_definition.sql
@@ function_definition.sql
@@ item_elem_2.sql
@@ using_clause.sql
@@ elsif_list.sql
@@ elsif_elem.sql
@@ error_logging_clause.sql
@@ returning_clause.sql
@@ dml_table_expression_clause.sql
@@ delete_statement.sql
@@ values_clause.sql
@@ bounds_clause.sql
@@ update_set_clause.sql
@@ update_set_clause_elem.sql
@@ insert_into_clause.sql
@@ single_table_insert.sql
@@ multi_table_insert.sql
@@ insert_statement.sql
@@ update_statement.sql
@@ dml_statement.sql
@@ commit_statement.sql
@@ set_transation_statement.sql
@@ rollback_statement.sql
@@ savepoint_statement.sql
@@ lock_table_statement.sql
@@ simple_case_statement.sql
@@ case_statement.sql
@@ cursor_for_loop_statement.sql
@@ close_statement.sql
@@ execute_immediate_statement.sql
@@ fetch_statement.sql
@@ for_loop_statement.sql
@@ forall_statement.sql
@@ open_for_statement.sql
@@ open_statement.sql
@@ simple_case_stmt_elem.sql
@@ select_into_statement.sql
@@ assignment_statement.sql
@@ basic_loop_statement.sql
@@ continue_statement.sql
@@ exit_statement.sql
@@ if_statement.sql
@@ return_statement.sql
@@ procedure_call.sql
@@ while_loop_statement.sql
@@ sql_statement.sql
@@ statement_elem.sql
@@ searched_case_stmt_elem.sql
@@ exception_list.sql
@@ exception_handler.sql
@@ exception.sql
@@ initialize_section.sql
@@ package.sql
@@ package_body.sql
